### ISSUE TITLE
Create structure for adding meeting notes and agendas for TGs

### ISSUE THREAD

**Issue by oej** [Ecma-TC54/meetings#4]
We need to store the notes somewhere here. It's currently on google docs for TG1

**Comment by jkowalleck** [comment]
we could open a repo for TG1 to TGn and give admin permissions to the respective TG leaders.
In these repos they could self-organic things. 

What do you think?

**Comment by oej** [comment]
That's perfect.

**Comment by jkowalleck** [comment]
@oej, you are admin of https://github.com/Ecma-TC54/tg1

**Comment by oej** [comment]
Ok, thank you!

**Comment by jkowalleck** [comment]
@stevespringett,

we have a (private) repo template for TGs here: https://github.com/Ecma-TC54/tgX
When creating a new repo, this can be selected as a template. 

We have a repo for 
- TG1 <https://github.com/Ecma-TC54/tg1>
  - @oej is admin 
- TG2 <https://github.com/Ecma-TC54/tg2>
  - no specific admins or collaborators

**Comment by jkowalleck** [comment]
(see how others manage/use their tg repo: https://github.com/tc39/tg3)
